name: rating
description: Rating bottom sheet
version: 1.0.0-dev.1
homepage: https://github.com/davidsdearaujo/rating

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

